setPostDataTV({
  ...postDataTV,
});

// TV Labour postData
const [postDataTV, setPostDataTV] = useState({
  tec_sup_qty_prep: 0,
  tec_sup_uno_prep: 0,
  tec_sup_una_prep: "",
  tec_sup_rt_prep: 0,
  tec_sup_qty_wrap: 0,
  tec_sup_uno_wrap: 0,
  tec_sup_una_wrap: "",
  tec_sup_rt_wrap: 0,
  tec_dir_qty_prep: 0,
  tec_dir_uno_prep: 0,
  tec_dir_una_prep: "",
  tec_dir_rt_prep: 0,
  tec_dir_qty_wrap: 0,
  tec_dir_uno_wrap: 0,
  tec_dir_una_wrap: "",
  tec_dir_rt_wrap: 0,
  flo_man_qty_prep: 0,
  flo_man_uno_prep: 0,
  flo_man_una_prep: "",
  flo_man_rt_prep: 0,
  flo_man_qty_wrap: 0,
  flo_man_uno_wrap: 0,
  flo_man_una_wrap: "",
  flo_man_rt_wrap: 0,
  lig_dir_qty_prep: 0,
  lig_dir_uno_prep: 0,
  lig_dir_una_prep: "",
  lig_dir_rt_prep: 0,
  lig_dir_qty_wrap: 0,
  lig_dir_uno_wrap: 0,
  lig_dir_una_wrap: "",
  lig_dir_rt_wrap: 0,
  boardm_qty_prep: 0,
  boardm_uno_prep: 0,
  boardm_una_prep: "",
  boardm_rt_prep: 0,
  boardm_qty_wrap: 0,
  boardm_uno_wrap: 0,
  boardm_una_wrap: "",
  boardm_rt_wrap: 0,
  audio_qty_prep: 0,
  audio_uno_prep: 0,
  audio_una_prep: "",
  audio_rt_prep: 0,
  audio_qty_wrap: 0,
  audio_uno_wrap: 0,
  audio_una_wrap: "",
  audio_rt_wrap: 0,
  vtr_op_qty_prep: 0,
  vtr_op_uno_prep: 0,
  vtr_op_una_prep: "",
  vtr_op_rt_prep: 0,
  vtr_op_qty_wrap: 0,
  vtr_op_uno_wrap: 0,
  vtr_op_una_wrap: "",
  vtr_op_rt_wrap: 0,
  stageh_qty_prep: 0,
  stageh_uno_prep: 0,
  stageh_una_prep: "",
  stageh_rt_prep: 0,
  stageh_qty_wrap: 0,
  stageh_uno_wrap: 0,
  stageh_una_wrap: "",
  stageh_rt_wrap: 0,
  oth_tv_qty_prep: 0,
  oth_tv_uno_prep: 0,
  oth_tv_una_prep: "",
  oth_tv_rt_prep: 0,
  oth_tv_qty_wrap: 0,
  oth_tv_uno_wrap: 0,
  oth_tv_una_wrap: "",
  oth_tv_rt_wrap: 0,
  fringes_taxes_tv: 0,
  tech_super_qty: 0,
  tech_super_uno: 0,
  tech_super_una: "",
  tech_super_rt: 0,
  tech_direct_qty: 0,
  tech_direct_uno: 0,
  tech_direct_una: "",
  tech_direct_rt: 0,
  floor_man_qty: 0,
  floor_man_uno: 0,
  floor_man_una: "",
  floor_man_rt: 0,
  light_direct_qty: 0,
  light_direct_uno: 0,
  light_direct_una: "",
  light_direct_rt: 0,
  boardman_qty: 0,
  boardman_uno: 0,
  boardman_una: "",
  boardman_rt: 0,
  audio_qty: 0,
  audio_uno: 0,
  audio_una: "",
  audio_rt: 0,
  vtr_operator_qty: 0,
  vtr_operator_uno: 0,
  vtr_operator_una: "",
  vtr_operator_rt: 0,
  stagehands_qty: 0,
  stagehands_uno: 0,
  stagehands_una: "",
  stagehands_rt: 0,
  other_tv_qty: 0,
  other_tv_uno: 0,
  other_tv_una: "",
  other_tv_rt: 0,
});

// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
  
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,

// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,