setPostDataElectric({
  ...postDataElectric,
});

// Electrical Labour postData grip next
const [postDataElectric, setPostDataElectric] = useState({
  gaf_qty_prep: 0,
  gaf_uno_prep: 0,
  gaf_una_prep: "",
  gaf_rt_prep: 0,
  gaf_qty_wrap: 0,
  gaf_uno_wrap: 0,
  gaf_una_wrap: "",
  gaf_rt_wrap: 0,
  b_boy_qty_prep: 0,
  b_boy_uno_prep: 0,
  b_boy_una_prep: "",
  b_boy_rt_prep: 0,
  b_boy_qty_wrap: 0,
  b_boy_uno_wrap: 0,
  b_boy_una_wrap: "",
  b_boy_rt_wrap: 0,
  elec_qty_prep: 0,
  elec_uno_prep: 0,
  elec_una_prep: "",
  elec_rt_prep: 0,
  elec_qty_wrap: 0,
  elec_uno_wrap: 0,
  elec_una_wrap: "",
  elec_rt_wrap: 0,
  gen_op_qty_prep: 0,
  gen_op_uno_prep: 0,
  gen_op_una_prep: "",
  gen_op_rt_prep: 0,
  gen_op_qty_wrap: 0,
  gen_op_uno_wrap: 0,
  gen_op_una_wrap: "",
  gen_op_rt_wrap: 0,
  ot_el_qty_prep: 0,
  ot_el_uno_prep: 0,
  ot_el_una_prep: "",
  ot_el_rt_prep: 0,
  ot_el_qty_wrap: 0,
  ot_el_uno_wrap: 0,
  ot_el_una_wrap: "",
  ot_el_rt_wrap: 0,
  d_elec_qty_prep: 0,
  d_elec_uno_prep: 0,
  d_elec_una_prep: "",
  d_elec_rt_prep: 0,
  d_elec_qty_wrap: 0,
  d_elec_uno_wrap: 0,
  d_elec_una_wrap: "",
  d_elec_rt_wrap: 0,
  fringes_taxes_electric: 0,
  gaffer_qty: 0,
  gaffer_uno: 0,
  gaffer_una: "",
  gaffer_rt: 0,
  best_boy_qty: 0,
  best_boy_uno: 0,
  best_boy_una: "",
  best_boy_rt: 0,
  electrician_qty: 0,
  electrician_uno: 0,
  electrician_una: "",
  electrician_rt: 0,
  dailies_elec_qty: 0,
  dailies_elec_uno: 0,
  dailies_elec_una: "",
  dailies_elec_rt: 0,
  generator_op_qty: 0,
  generator_op_uno: 0,
  generator_op_una: "",
  generator_op_rt: 0,
  other_elec_qty: 0,
  other_elec_uno: 0,
  other_elec_una: "",
  other_elec_rt: 0,
});

// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
// staaaaaaars: shoot_global,
  
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,
// staaaaaaars: prep_global,

// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,
// staaaaaaars: wrap_global,